spring:
  application:
    name: vue-manager
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_db?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
    druid:
      connection-error-retry-attempts: 2
server:
  port: 8080


