spring:
  application:
    name: vue-manager
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue_manager
    username: root
    password: 123456
server:
  port: 8080


